#!/usr/bin/python
#################################
#For lops with lists
#      Name : Sifa Lookia
#      Date : 24 / 05 /2022
##################################

squares = []#empty list
for numbers in range (0, 10):
    square = (numbers**2)
    squares.append(square)


